services:
  backend:
    build:
      context: ./ImperialBackend
      dockerfile: Dockerfile.prod
    container_name: imperial_backend
    environment:
      ASPNETCORE_URLS: "http://+:5032"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=ImperialDb_New;User Id=sa;Password=SomeStrongPassword123!;Encrypt=False;TrustServerCertificate=True;MultipleActiveResultSets=True"
    ports:
      - "5032:5032"
    depends_on:
      - db

  frontend:
    build:
      context: ./ImperialFrontend
      dockerfile: Dockerfile.prod
    container_name: imperial_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: imperial_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SomeStrongPassword123!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
