services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: raid-rabbit
    hostname: raid-rabbit

    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI

    environment:
      RABBITMQ_DEFAULT_USER: imperial
      RABBITMQ_DEFAULT_PASS: ImperialGuild
      RABBITMQ_DEFAULT_VHOST: imperial
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: >
        -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./RabbitMQ/definitions.json:/etc/rabbitmq/definitions.json:ro

    networks:
      - imperial-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  rabbitmq-data:

networks:
  imperial-net:
    name: imperial-net
    driver: bridge
