# ------------------------
# Build Stage
# ------------------------
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# copy csproj file(s)
COPY Backend.csproj ./

# restore
RUN dotnet restore

# copy everything else and build
COPY . .

# publish for production
RUN dotnet publish -c Release -o /app/publish

# ------------------------
# Runtime Stage
# ------------------------
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 5032
ENTRYPOINT ["dotnet", "Backend.dll"]