// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(WynncraftDbContext))]
    [Migration("20251218072456_CorrectRenameSeasonRaitingToSeasonRating")]
    partial class CorrectRenameSeasonRaitingToSeasonRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("EventEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Backend.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Backend.Models.GuildMember", b =>
                {
                    b.Property<int>("GuildMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuildMemberId"));

                    b.Property<string>("DiscordTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSynced")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinecraftUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WarsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("WeekliesCompleted")
                        .HasColumnType("int");

                    b.Property<string>("WynncraftRank")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuildMemberId");

                    b.HasIndex("RankId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("Backend.Models.GuildMemberGame", b =>
                {
                    b.Property<int>("GuildMemberGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuildMemberGameId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("int");

                    b.HasKey("GuildMemberGameId");

                    b.HasIndex("GuildMemberId");

                    b.HasIndex("GameId", "GuildMemberId")
                        .IsUnique();

                    b.ToTable("GuildMemberGames");
                });

            modelBuilder.Entity("Backend.Models.GuildMemberMedal", b =>
                {
                    b.Property<int>("GuildMemberMedalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuildMemberMedalId"));

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("int");

                    b.Property<int>("MedalId")
                        .HasColumnType("int");

                    b.HasKey("GuildMemberMedalId");

                    b.HasIndex("GuildMemberId");

                    b.HasIndex("MedalId", "GuildMemberId")
                        .IsUnique();

                    b.ToTable("GuildMemberMedals");
                });

            modelBuilder.Entity("Backend.Models.Medal", b =>
                {
                    b.Property<int>("MedalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedalId"));

                    b.Property<string>("MedalName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedalId");

                    b.ToTable("Medals");
                });

            modelBuilder.Entity("Backend.Models.PlayerHistoricalStat", b =>
                {
                    b.Property<int>("StatHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatHistoryId"));

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("int");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("int");

                    b.Property<DateTime>("SyncDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("WeekliesCompleted")
                        .HasColumnType("int");

                    b.HasKey("StatHistoryId");

                    b.HasIndex("GuildMemberId");

                    b.ToTable("PlayerHistoricalStats");
                });

            modelBuilder.Entity("Backend.Models.Raid", b =>
                {
                    b.Property<int>("RaidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaidId"));

                    b.Property<string>("RaidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonRating")
                        .HasColumnType("int");

                    b.HasKey("RaidId");

                    b.ToTable("Raids");
                });

            modelBuilder.Entity("Backend.Models.RaidCompleted", b =>
                {
                    b.Property<int>("RaidCompletedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaidCompletedId"));

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuildMemberId")
                        .HasColumnType("int");

                    b.Property<int>("RaidId")
                        .HasColumnType("int");

                    b.Property<int>("RaidInstanceId")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RaidCompletedId");

                    b.HasIndex("GuildMemberId");

                    b.HasIndex("RaidId");

                    b.ToTable("RaidsCompleted");
                });

            modelBuilder.Entity("Backend.Models.Rank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RankId"));

                    b.Property<string>("RankName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RankId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("Backend.Models.GuildMember", b =>
                {
                    b.HasOne("Backend.Models.Rank", "Rank")
                        .WithMany("GuildMembers")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Backend.Models.GuildMemberGame", b =>
                {
                    b.HasOne("Backend.Models.Game", "Game")
                        .WithMany("GuildMemberGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.GuildMember", "GuildMember")
                        .WithMany("Games")
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GuildMember");
                });

            modelBuilder.Entity("Backend.Models.GuildMemberMedal", b =>
                {
                    b.HasOne("Backend.Models.GuildMember", "GuildMember")
                        .WithMany("Medals")
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Medal", "Medal")
                        .WithMany("GuildMemberMedals")
                        .HasForeignKey("MedalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMember");

                    b.Navigation("Medal");
                });

            modelBuilder.Entity("Backend.Models.PlayerHistoricalStat", b =>
                {
                    b.HasOne("Backend.Models.GuildMember", "GuildMember")
                        .WithMany("PlayerHistoricalStats")
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMember");
                });

            modelBuilder.Entity("Backend.Models.RaidCompleted", b =>
                {
                    b.HasOne("Backend.Models.GuildMember", "GuildMember")
                        .WithMany()
                        .HasForeignKey("GuildMemberId");

                    b.HasOne("Backend.Models.Raid", "Raid")
                        .WithMany("RaidsCompleted")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMember");

                    b.Navigation("Raid");
                });

            modelBuilder.Entity("Backend.Models.Game", b =>
                {
                    b.Navigation("GuildMemberGames");
                });

            modelBuilder.Entity("Backend.Models.GuildMember", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Medals");

                    b.Navigation("PlayerHistoricalStats");
                });

            modelBuilder.Entity("Backend.Models.Medal", b =>
                {
                    b.Navigation("GuildMemberMedals");
                });

            modelBuilder.Entity("Backend.Models.Raid", b =>
                {
                    b.Navigation("RaidsCompleted");
                });

            modelBuilder.Entity("Backend.Models.Rank", b =>
                {
                    b.Navigation("GuildMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
