// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(WynncraftDbContext))]
    [Migration("20260104111952_RaidsCompletedChange")]
    partial class RaidsCompletedChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTimeOffset>("EventEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EventStart")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EventId");

                    b.HasIndex("EventStart")
                        .HasDatabaseName("IX_Events_EventStart");

                    b.HasIndex("EventStart", "EventEnd")
                        .HasDatabaseName("IX_Events_EventStart_EventEnd");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Backend.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GameId");

                    b.HasIndex("GameName")
                        .HasDatabaseName("IX_Games_GameName");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Backend.Models.GuildMember", b =>
                {
                    b.Property<int>("GuildMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuildMemberId"));

                    b.Property<string>("DiscordTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("int");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastSynced")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MainUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinecraftUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WarsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("WeekliesCompleted")
                        .HasColumnType("int");

                    b.Property<string>("WynncraftRank")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuildMemberId");

                    b.HasIndex("LastSynced")
                        .HasDatabaseName("IX_GuildMembers_LastSynced");

                    b.HasIndex("MinecraftUsername")
                        .HasDatabaseName("IX_GuildMembers_MinecraftUsername");

                    b.HasIndex("RankId")
                        .HasDatabaseName("IX_GuildMembers_RankId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("Backend.Models.GuildMemberGame", b =>
                {
                    b.Property<int>("GuildMemberGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuildMemberGameId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("int");

                    b.HasKey("GuildMemberGameId");

                    b.HasIndex("GameId")
                        .HasDatabaseName("IX_GuildMemberGames_GameId");

                    b.HasIndex("GuildMemberId")
                        .HasDatabaseName("IX_GuildMemberGames_GuildMemberId");

                    b.HasIndex("GameId", "GuildMemberId")
                        .IsUnique();

                    b.ToTable("GuildMemberGames");
                });

            modelBuilder.Entity("Backend.Models.GuildMemberMedal", b =>
                {
                    b.Property<int>("GuildMemberMedalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuildMemberMedalId"));

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("int");

                    b.Property<int>("MedalId")
                        .HasColumnType("int");

                    b.HasKey("GuildMemberMedalId");

                    b.HasIndex("GuildMemberId")
                        .HasDatabaseName("IX_GuildMemberMedals_GuildMemberId");

                    b.HasIndex("MedalId")
                        .HasDatabaseName("IX_GuildMemberMedals_MedalId");

                    b.HasIndex("MedalId", "GuildMemberId")
                        .IsUnique();

                    b.ToTable("GuildMemberMedals");
                });

            modelBuilder.Entity("Backend.Models.Medal", b =>
                {
                    b.Property<int>("MedalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedalId"));

                    b.Property<string>("MedalName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedalId");

                    b.ToTable("Medals");
                });

            modelBuilder.Entity("Backend.Models.PlayerHistoricalStat", b =>
                {
                    b.Property<int>("StatHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatHistoryId"));

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("int");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SyncDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WarsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("WeekliesCompleted")
                        .HasColumnType("int");

                    b.HasKey("StatHistoryId");

                    b.HasIndex("GuildMemberId")
                        .HasDatabaseName("IX_PlayerHistoricalStats_GuildMemberId");

                    b.HasIndex("GuildMemberId", "SyncDate")
                        .HasDatabaseName("IX_PlayerHistoricalStats_GuildMemberId_SyncDate");

                    b.ToTable("PlayerHistoricalStats");
                });

            modelBuilder.Entity("Backend.Models.Raid", b =>
                {
                    b.Property<int>("RaidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaidId"));

                    b.Property<string>("RaidName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonRating")
                        .HasColumnType("int");

                    b.HasKey("RaidId");

                    b.ToTable("Raids");
                });

            modelBuilder.Entity("Backend.Models.RaidCompleted", b =>
                {
                    b.Property<int>("RaidCompletedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaidCompletedId"));

                    b.Property<DateTimeOffset>("CompletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RaidId")
                        .HasColumnType("int");

                    b.HasKey("RaidCompletedId");

                    b.HasIndex("CompletedDate")
                        .HasDatabaseName("IX_RaidsCompleted_CompletedDate");

                    b.HasIndex("RaidId")
                        .HasDatabaseName("IX_RaidsCompleted_RaidId");

                    b.HasIndex("RaidId", "CompletedDate")
                        .HasDatabaseName("IX_RaidsCompleted_RaidId_CompletedDate");

                    b.ToTable("RaidsCompleted");
                });

            modelBuilder.Entity("Backend.Models.RaidInstance", b =>
                {
                    b.Property<int>("RaidInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaidInstanceId"));

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("int");

                    b.Property<int>("RaidCompletedId")
                        .HasColumnType("int");

                    b.HasKey("RaidInstanceId");

                    b.HasIndex("GuildMemberId")
                        .HasDatabaseName("IX_RaidInstances_GuildMemberId");

                    b.HasIndex("RaidCompletedId")
                        .HasDatabaseName("IX_RaidInstances_RaidCompletedId");

                    b.HasIndex("RaidCompletedId", "GuildMemberId")
                        .IsUnique()
                        .HasDatabaseName("UX_RaidInstances_RaidCompletedId_GuildMemberId");

                    b.ToTable("RaidInstances");
                });

            modelBuilder.Entity("Backend.Models.Rank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RankId"));

                    b.Property<string>("RankName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RankId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("Backend.Models.GuildMember", b =>
                {
                    b.HasOne("Backend.Models.Rank", "Rank")
                        .WithMany("GuildMembers")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Backend.Models.GuildMemberGame", b =>
                {
                    b.HasOne("Backend.Models.Game", "Game")
                        .WithMany("GuildMemberGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.GuildMember", "GuildMember")
                        .WithMany("Games")
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GuildMember");
                });

            modelBuilder.Entity("Backend.Models.GuildMemberMedal", b =>
                {
                    b.HasOne("Backend.Models.GuildMember", "GuildMember")
                        .WithMany("Medals")
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Medal", "Medal")
                        .WithMany("GuildMemberMedals")
                        .HasForeignKey("MedalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMember");

                    b.Navigation("Medal");
                });

            modelBuilder.Entity("Backend.Models.PlayerHistoricalStat", b =>
                {
                    b.HasOne("Backend.Models.GuildMember", "GuildMember")
                        .WithMany("PlayerHistoricalStats")
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMember");
                });

            modelBuilder.Entity("Backend.Models.RaidCompleted", b =>
                {
                    b.HasOne("Backend.Models.Raid", "Raid")
                        .WithMany("RaidsCompleted")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raid");
                });

            modelBuilder.Entity("Backend.Models.RaidInstance", b =>
                {
                    b.HasOne("Backend.Models.GuildMember", "GuildMember")
                        .WithMany()
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.RaidCompleted", "RaidCompleted")
                        .WithMany("RaidInstances")
                        .HasForeignKey("RaidCompletedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMember");

                    b.Navigation("RaidCompleted");
                });

            modelBuilder.Entity("Backend.Models.Game", b =>
                {
                    b.Navigation("GuildMemberGames");
                });

            modelBuilder.Entity("Backend.Models.GuildMember", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Medals");

                    b.Navigation("PlayerHistoricalStats");
                });

            modelBuilder.Entity("Backend.Models.Medal", b =>
                {
                    b.Navigation("GuildMemberMedals");
                });

            modelBuilder.Entity("Backend.Models.Raid", b =>
                {
                    b.Navigation("RaidsCompleted");
                });

            modelBuilder.Entity("Backend.Models.RaidCompleted", b =>
                {
                    b.Navigation("RaidInstances");
                });

            modelBuilder.Entity("Backend.Models.Rank", b =>
                {
                    b.Navigation("GuildMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
