namespace ImperialBackend.DTOs
{
    public class RaidPostDTO
    {
        //id is NOT autogenerated due to mapping from raid bot
        public int RaidId { get; set; }
        public string? RaidName { get; set; }
        public int SeasonRating { get; set; }
    }
}
