using ImperialBackend.Models;

namespace ImperialBackend.DTOs
{
    public class RaidPostDTO : GenericPostDTO
    {
        //id is NOT autogenerated due to mapping from raid bot
        public int Id { get; set; }
        public int SeasonRating { get; set; }
    }
}
